# Generated by Django 5.0.6 on 2024-06-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Expense_category',
        ),
    ]
