# Generated by Django 5.0.6 on 2024-08-10 17:22

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=management.models.store_logo_upload_path),
        ),
    ]
