# Generated by Django 5.0.6 on 2024-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled')], max_length=64),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
