# Generated by Django 5.0.6 on 2024-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_order_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
