# Generated by Django 5.0.6 on 2024-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_order_payment_method_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrdersTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
